"use client";

import { useActionState, useState } from "react";
import { startEnrol, verifyEnrol, type EnrolState } from "./actions";

const initialState: EnrolState = {};

/**
 * Two-step enrolment. Round 1 verifies the first code; success redirects to
 * ?step=2 (round 2 verifies the second code, then redirects to the completion
 * page). Redirects — not action state — carry the flow forward, because
 * post-rotation action responses are superseded by a fresh server render.
 */
export default function EnrolMfa({ round2FactorId }: { round2FactorId: string | null }) {
  const [state, action, pending] = useActionState(verifyEnrol, initialState);
  const [started, setStarted] = useState<EnrolState | null>(null);
  const [starting, setStarting] = useState(false);
  const [code, setCode] = useState("");

  const factorId = state.factorId ?? started?.factorId ?? round2FactorId;
  const round2 = !!round2FactorId;

  async function begin() {
    setStarting(true);
    try {
      setStarted(await startEnrol());
    } finally {
      setStarting(false);
    }
  }

  if (!factorId) {
    return (
      <main>
        <h1>Set up authenticator</h1>
        <p>Scan the code with your authenticator app, then enter two codes.</p>
        {started?.error ? <p role="alert">{started.error}</p> : null}
        <button type="button" onClick={begin} disabled={starting}>
          Start setup
        </button>
      </main>
    );
  }

  return (
    <main>
      <h1>{round2 ? "Enter second code" : "Enter first code"}</h1>
      {started?.qrCode && !round2 ? (
        <div
          // QR is generated by Supabase Auth (first-party), not user input.
          dangerouslySetInnerHTML={{ __html: started.qrCode }}
        />
      ) : null}
      {started?.secret && !round2 ? (
        <>
          <p>Manual entry code:</p>
          <p>
            <code>{started.secret}</code>
          </p>
        </>
      ) : null}
      <form action={action}>
        <input type="hidden" name="factorId" value={factorId} />
        {round2 ? <input type="hidden" name="round" value="2" /> : null}
        <label htmlFor="code">6-digit code</label>
        <input
          id="code"
          name="code"
          type="text"
          required
          inputMode="numeric"
          autoComplete="one-time-code"
          value={code}
          onChange={(e) => setCode(e.target.value)}
        />
        {state.error || started?.error ? <p role="alert">{state.error ?? started?.error}</p> : null}
        <button type="submit" disabled={pending}>
          Verify
        </button>
      </form>
    </main>
  );
}
