"use client";

import { useActionState, useState } from "react";
import { finishEnrol, startEnrol, verifyEnrol, type EnrolState } from "./actions";

const initialState: EnrolState = {};

export default function EnrolMfa() {
  const [state, action, pending] = useActionState(verifyEnrol, initialState);
  const [started, setStarted] = useState<EnrolState | null>(null);
  const [starting, setStarting] = useState(false);
  const [code, setCode] = useState("");
  const [saved, setSaved] = useState(false);

  const active: EnrolState = state.factorId || state.codes ? state : (started ?? {});
  const factorId = active.factorId ?? started?.factorId;

  async function begin() {
    setStarting(true);
    try {
      setStarted(await startEnrol());
    } finally {
      setStarting(false);
    }
  }

  if (active.codes) {
    return (
      <main>
        <h1>Save recovery codes</h1>
        <p>
          These 10 codes are shown once. They are never emailed or shown again. Each works once if
          you lose your authenticator.
        </p>
        <ol>
          {active.codes.map((c) => (
            <li key={c}>
              <code>{c}</code>
            </li>
          ))}
        </ol>
        <label htmlFor="saved">I saved these codes somewhere safe</label>
        <input
          id="saved"
          type="checkbox"
          checked={saved}
          onChange={(e) => setSaved(e.target.checked)}
        />
        <form action={finishEnrol}>
          <button type="submit" disabled={!saved}>
            Done
          </button>
        </form>
      </main>
    );
  }

  if (!factorId) {
    return (
      <main>
        <h1>Set up authenticator</h1>
        <p>Scan the code with your authenticator app, then enter two codes.</p>
        {started?.error ? <p role="alert">{started.error}</p> : null}
        <button type="button" onClick={begin} disabled={starting}>
          Start setup
        </button>
      </main>
    );
  }

  return (
    <main>
      <h1>{active.needsSecond ? "Enter second code" : "Enter first code"}</h1>
      {started?.qrCode && !active.needsSecond ? (
        <div
          // QR is generated by Supabase Auth (first-party), not user input.
          dangerouslySetInnerHTML={{ __html: started.qrCode }}
        />
      ) : null}
      {started?.secret ? (
        <>
          <p>Manual entry code:</p>
          <p>
            <code>{started.secret}</code>
          </p>
        </>
      ) : null}
      <form action={action}>
        <input type="hidden" name="factorId" value={factorId} />
        {active.needsSecond ? <input type="hidden" name="round" value="2" /> : null}
        <label htmlFor="code">6-digit code</label>
        <input
          id="code"
          name="code"
          type="text"
          required
          inputMode="numeric"
          autoComplete="one-time-code"
          value={code}
          onChange={(e) => setCode(e.target.value)}
        />
        {active.error ? <p role="alert">{active.error}</p> : null}
        <button type="submit" disabled={pending}>
          Verify
        </button>
      </form>
    </main>
  );
}
